---
apiVersion: v1
kind: Pod
metadata:
  name: bluepod
  labels:
    app: samplebluegreen
    version: v1 
spec:
  containers:
  - name: samplehtml
    image: sam:0.1
    ports:
      - containerPort: 80
...
