---
apiVersion: v1
kind: Namespace
metadata:
  name: namens
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampledeploy
  namespace: namens
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: htmlwebapp
  template:
    metadata:
      name: samplepod
      labels:
        app: htmlwebapp
    spec:
      containers:
      - name: samplecontainer
        image: akshay0909/sam:1.0
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: samplesvc
  namespace: namens
spec:
  type: NodePort
  selector:
    app: htmlwebapp
  ports:
  - port: 80  # External port for the service 
    targetPort: 80  # Internal port on the container
    nodePort: 30786  # Port on the node
...
