apiVersion: v1
kind: Namespace
metadata:
  name: samplens

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampledeploy
  namespace: samplens
spec: 
  replicas: 4
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels: 
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
       containers:
       - name: samplecont
         image: nginx
         ports:
         - containerPort: 80
         resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
         volumeMounts:
         - name: samplevol
           mountPath: /app
      volumes:
      - name: samplevol
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata: 
  name: samplesvc
  namespace: samplens 
spec:
  type: NodePort
  selector:
    app: sampleapp
  ports:
  - port: 80
    targetPort: 80 
    nodePort: 32767
